package com.ran.mall.entity.bean

import java.io.Serializable
/**
 */

data class ReportTaskDetailInfo(
        var _id: String = "",
        var id: String = "",
        var reportId: String = "",
        var agentId: AgentId,
        var flowId: String = "",
        var channel: String = "",
        var date: String = "",
        var reasonAccid: ArrayList<String> ?= null,
        var isReturn: Boolean = false,
        var reasonThisReturn: ArrayList<String> ?= null,
        var ownCarLoss: OwnCarLoss,
        var carNumber: String = "",
        var accidentDate: String = "",
        var accidentTime: String = "",
        var place: String = "",
        var lossConfirm: Boolean = false,
        var surveyConfirm: Boolean = false,
        var accidentDetail: String = "",
        var reporter: String = "",
        var reporterCellPhone: String = "",
        var otherCarLoss: ArrayList<OtherCarLoss>,
        var peoples: ArrayList<PeopleInfo>,
        var articles: ArrayList<ArticleInfo>,
        var reporterRelationship: String = "000",
        var dsImageUploading: Boolean = false,
        var isEarlyStage: Boolean = false,
        var surveyOperater: String = "",
        var surveyPhone: String = "",
        var surveyTime: String = "",
        var directPayOther: String = "",
        var surveyType: String = "",
        var supervisePhone: String = "",
        var surveyConclude: String = ""

):Serializable

data class AgentId(
        var _id: String = "",
        var cellphone: String = "",
        var loginName: String = "",
        var fullName: String = "",
        var province: String = "",
        var city: String = "",
        var carOwner: String = ""
):Serializable

data class PeopleInfo(
        var _id: String = "",
        var type: String = "",
        var money: String = "",
        var isPayed: Boolean = false,
        var inCar: String = "",
        var carType: String = "",
        var isSigned: Boolean = false,
        var needResign: Boolean = false,
        var carNumber: String = "",
        var cellPhone: String = "",
        var carOwner: String = "",
        var idCard: IDCard? = null,
        var accidentResponse: String = "",
        var carLossInfo: String = "",
        var reputer: String = "",
        var reputOrg: String = "",
        var reputPhone: String = "",
        var hurt: MutableList<String> ?= null,
        var hurtLevel: String = "",
        var IdFront: MutableList<CarPics>? = null,
        var IdRevert: MutableList<CarPics>? = null,
        var driverMain: MutableList<CarPics>? = null,
        var driverSide: MutableList<CarPics>? = null,
        var drivingMain: MutableList<CarPics>? = null,
        var drivingSide: MutableList<CarPics>? = null,
        var drivingSide2: MutableList<CarPics>? = null,
        var bankCardPics: MutableList<CarPics>? = null,
        var otherCardPics: MutableList<CarPics>? = null,
        var carPics: MutableList<CarPics> ? = null,
        var newAdd: Boolean = false,
        var directStorePay: Boolean = false
):Serializable

data class ArticleInfo(
        var _id: String = "",
        var type: String = "",
        var owner: String = "",
        var isPayed: Boolean = false,
        var value: String = "",
        var money: String = "",
        var inCar: String = "",
        var carType: String = "",
        var isSigned: Boolean = false,
        var needResign: Boolean = false,
        var carNumber: String = "",
        var cellPhone: String = "",
        var carOwner: String = "",
        var idCard: IDCard? = null,
        var accidentResponse: String = "",
        var carLossInfo: String = "",
        var reputer: String = "",
        var reputOrg: String = "",
        var reputPhone: String = "",
        var hurt: MutableList<String> ?= null,
        var hurtLevel: String = "",
        var IdFront: MutableList<CarPics>? = null,
        var IdRevert: MutableList<CarPics>? = null,
        var driverMain: MutableList<CarPics>? = null,
        var driverSide: MutableList<CarPics>? = null,
        var drivingMain: MutableList<CarPics>? = null,
        var drivingSide: MutableList<CarPics>? = null,
        var drivingSide2: MutableList<CarPics>? = null,
        var bankCardPics: MutableList<CarPics>? = null,
        var otherCardPics: MutableList<CarPics>? = null,
        var carPics: MutableList<CarPics> ? = null,
        var newAdd: Boolean = false,
        var directStorePay: Boolean = false
):Serializable

data class OwnCarLoss(
        var _id: String = "",
        var type: String = "",
        var isSigned: Boolean = false,
        var needResign: Boolean = false,
        var carNumber: String = "",
        var cellPhone: String = "",
        var carOwner: String = "",
        var idCard: IDCard? = null,
        var accidentResponse: String = "",
        var carLossInfo: String = "",
        var reputer: String = "",
        var reputOrg: String = "",
        var reputPhone: String = "",
        var hurt: MutableList<String> ?= null,
        var hurtType: MutableList<String> ?= null,
        var IdFront: MutableList<CarPics>,
        var IdRevert: MutableList<CarPics>,
        var driverMain: MutableList<CarPics>,
        var driverSide: MutableList<CarPics>,
        var drivingMain: MutableList<CarPics>,
        var drivingSide: MutableList<CarPics>,
        var drivingSide2: MutableList<CarPics>,
        var bankCardPics: MutableList<CarPics>,
        var otherCardPics: MutableList<CarPics>,
        var carPics: MutableList<CarPics>,
        var directStorePay: Boolean = false
):Serializable

data class CarPics(
        var _id: String = "",
        var original_url: String = "",
        var thumbnail_url: String = "",
        var url: String = "",
        var dsUploading: Boolean = false,
        var uploaded: Boolean = false,
        var userUpload: Boolean = false
):Serializable

data class OtherCarLoss(
        var _id: String = "",
        var type: String = "",
        var isSigned: Boolean = false,
        var carNumber: String = "",
        var cellPhone: String = "",
        var carOwner: String = "",
        var idCard: IDCard ? = null,
        var accidentResponse: String = "",
        var carLossInfo: String = "",
        var reputer: String = "",
        var reputOrg: String = "",
        var reputPhone: String = "",
        var hurt: MutableList<String> ?= null,
        var hurtType: MutableList<String> ?= null,
        var IdFront: MutableList<CarPics>? = null,
        var IdRevert: MutableList<CarPics>? = null,
        var driverMain: MutableList<CarPics>? = null,
        var driverSide: MutableList<CarPics>? = null,
        var drivingMain: MutableList<CarPics>? = null,
        var drivingSide: MutableList<CarPics>? = null,
        var drivingSide2: MutableList<CarPics>? = null,
        var bankCardPics: MutableList<CarPics>? = null,
        var otherCardPics: MutableList<CarPics>? = null,
        var carPics: MutableList<CarPics> ? = null,
        var brand: String = "",
        var newAdd: Boolean = false,
        var directStorePay: Boolean = false

):Serializable
data class IDCard(
        var id: String = ""
):Serializable